config/routes.rb
Logkeeper::Application.routes.draw do
  root :to => "organizations#index"

  devise_for :users

  resources :organizations, :only => [:index, :show, :new, :create] do
    resources :logbooks, :only => [:show, :new, :create] do
      resources :pages, :only => [:show] do
        resources :entries, :only => [:new, :create]
      end
    end
  end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :page
  belongs_to :user

  validates_presence_of :page_id
  validates_presence_of :text
  validates_presence_of :user_id
end

app/models/logbook.rb
class Logbook < ActiveRecord::Base
  belongs_to :organization

  has_many :pages

  validates_length_of :name, :within => 1..100
  validates_presence_of :name
  validates_presence_of :organization_id
  validate :duplicate_logbook_name_in_organization

  def posted_pages
    pages.where(:is_posted => true)
  end

  def create_first_page
    Page.create_first_page(self)
  end

  private

  def duplicate_logbook_name_in_organization
    errors.add :name, "already exists with that name" if Logbook.exists?(:organization_id => organization_id, :name => name)
  end
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :logbooks
  has_many :organization_users
  has_many :users, :through => :organization_users

  validates_length_of :name, :within => 1..100
  validates_presence_of :name
  validates_uniqueness_of :name, :case_sensitive => false
end

app/models/organization_user.rb
class OrganizationUser < ActiveRecord::Base
  belongs_to :organization
  belongs_to :user

  validates_presence_of :organization_id
  validates_presence_of :role
  validates_presence_of :user_id

  def create_owner_organization_and_user_connection(user, organization)
    self.user, self.organization, self.role = user, organization, 'owner'
    self.save
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :logbook

  has_many :entries

  validates_inclusion_of :is_posted, :in => [true, false]
  validates_length_of :name, :within => 1..100
  validates_presence_of :logbook_id
  validates_presence_of :name
  validates_presence_of :scheduled_at

  def schedule_next_page(logbook, time)
    scheduled_time = time.beginning_of_day + 1.day
    page = Page.create!(:logbook => logbook, :scheduled_at => scheduled_time, :name => scheduled_time.strftime('%A, %B %-d, %Y'))
    page.post_next_page
  end

  def post_next_page
    self.update_attributes(:is_posted => true)
    schedule_next_page(logbook, scheduled_at)
  end

  handle_asynchronously :post_next_page, :run_at => Proc.new { |p| p.scheduled_at }

  private

  def self.create_first_page(logbook)
    time = Time.zone.now
    page = Page.create!(:logbook => logbook, :scheduled_at => time, :name => time.strftime('%A, %B %-d, %Y'), :is_posted => true)
    page.schedule_next_page(logbook, time)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_many :entries
  has_many :organization_users
  has_many :organizations, :through => :organization_users

  validates :email, :email => true
  validates_length_of :email, :within => 6..100 # a@a.co
  validates_length_of :first_name, :within => 1..50
  validates_length_of :last_name, :within => 1..50
  validates_presence_of :email
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :password
  validates_presence_of :password_confirmation
  validates_uniqueness_of :email, :case_sensitive => false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, :if => :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation) }
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_organization
  before_filter :load_logbook
  before_filter :load_page

  def new
    @entry = Entry.new
  end

  def create
    @entry = Entry.new(entry_params)
    @entry.update_attributes(:page => @page, :user => current_user)

    if @entry.save
      redirect_to organization_logbook_page_path(@organization, @logbook, @page), :notice => 'Entry has been posted.'
    else
      render 'new'
    end
  end

  private

  def entry_params
    params.require(:entry).permit(:text)
  end

  def load_organization
    @organization = Organization.find(params.require(:organization_id))
  end

  def load_logbook
    @logbook = Logbook.find(params.require(:logbook_id))
  end

  def load_page
    @page = Page.find(params.require(:page_id))
  end
end

app/controllers/logbooks_controller.rb
class LogbooksController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_organization

  def show
    @logbook = Logbook.find(params.require(:id))
  end

  def new
    @logbook = Logbook.new
  end

  def create
    @logbook = Logbook.new(logbook_params)

    if @logbook.save
      @logbook.create_first_page
      redirect_to organization_path(@organization), :notice => 'Logbook has been successfully created.'
    else
      render 'new'
    end
  end

  private

  def load_organization
    @organization = Organization.find(params.require(:organization_id))
  end

  def logbook_params
    params.require(:logbook).permit(:name).merge(:organization => @organization)
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @organizations = current_user.organizations
  end

  def show
    @organization = Organization.find(params.require(:id))
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(organization_params)
    @organization_user = OrganizationUser.new

    if @organization.save
      @organization_user.create_owner_organization_and_user_connection(current_user, @organization)
      redirect_to organizations_path, :notice => 'Organization has been successfully created.'
    else
      render 'new'
    end
  end

  private

  def organization_params
    params.require(:organization).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_organization
  before_filter :load_logbook

  def show
    @page = Page.find(params.require(:id))
  end

  private

  def load_organization
    @organization = Organization.find(params.require(:organization_id))
  end

  def load_logbook
    @logbook = Logbook.find(params.require(:logbook_id))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>"><%= value %></div>
  <% end -%>
</div>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/entries/new.html.erb
<h2>New Entry</h2>

<%= simple_form_for [@organization, @logbook, @page, @entry] do |f| %>
  <div class="form-inputs">
    <%= f.input :text, :required => true, :autofocus => true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Post entry" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <title><%= page_title %></title>
  <%= stylesheet_link_tag :application, :media => 'all' %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= render 'flashes' -%>
  <%= yield %>
  <%= render 'javascript' %>
</body>
</html>

app/views/logbooks/new.html.erb
<h2>New Logbook</h2>

<%= simple_form_for [@organization, @logbook] do |f| %>
  <div class="form-inputs">
    <%= f.input :name, :required => true, :autofocus => true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Create logbook" %>
  </div>
<% end %>

app/views/logbooks/show.html.erb
<h1><%= @logbook.name %></h1>

<% if @logbook.pages.empty? %>
  <p>No pages currently exist.</p>
<% else %>
  <div class='logbook_list'>
    <ul>
      <% @logbook.posted_pages.each do |p| %>
        <li><%= link_to "#{p.name}", organization_logbook_page_path(@organization, @logbook, p) %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/organizations/index.html.erb
<h1>Organizations</h1>

<% if current_user.organizations.empty? %>
  <p>You are currently not a part of any organizations.</p>
<% else %>
  <div class='organization_list'>
    <ul>
      <% current_user.organizations.each do |o| %>
        <li><%= link_to "#{o.name}", organization_path(o) %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<p><%= link_to 'Create new organization', new_organization_path %></p>

app/views/organizations/new.html.erb
<h2>New Organization</h2>

<%= simple_form_for @organization do |f| %>
  <div class="form-inputs">
    <%= f.input :name, :required => true, :autofocus => true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Create organization" %>
  </div>
<% end %>

app/views/organizations/show.html.erb
<h1><%= @organization.name %></h1>

<% if @organization.logbooks.empty? %>
  <p>No logbooks currently exist.</p>
<% else %>
  <div class='logbook_list'>
    <ul>
      <% @organization.logbooks.each do |l| %>
        <li><%= link_to "#{l.name}", organization_logbook_path(@organization, l) %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<p><%= link_to 'Create new logbook', new_organization_logbook_path(@organization) %></p>

app/views/pages/home.html.erb
<h1>It works!</h1>
<% if current_user %>
  <p>Hello, <%= current_user.email %> <%= link_to '(sign out)', destroy_user_session_path %></p>
  <p><%= link_to 'Create new organization', new_organization_path %>
<% else %>
  <p><%= link_to 'Sign in', new_user_session_path %>
<% end %>

app/views/pages/show.html.erb
<h1><%= @page.name %></h1>

<% if @page.entries.empty? %>
  <p>No entries currently exist.</p>
<% else %>
  <div class='entries_list'>
    <ul>
      <% @page.entries.each do |e| %>
        <li><%= "#{e.text}" %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<p><%= link_to 'Post new entry', new_organization_logbook_page_entry_path(@organization, @logbook, @page) %></p>

app/views/site/placeholder.html.erb
<h1>It works!</h1>
<% if current_user %>
  <p>Hello, <%= current_user.email %> <%= link_to '(sign out)', destroy_user_session_path %></p>
  <p><%= link_to 'Create new organization', new_organization_path %>
<% else %>
  <p><%= link_to 'Sign in', new_user_session_path %>
<% end %>